# Generated by Django 4.2.7 on 2024-10-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQ5nJ-946STbB6QZQbKiW60QJI3ajOjE43Qg&s.png', max_length=500),
        ),
    ]
